### ISSUE TITLE
Samples & Speed

### ISSUE THREAD

**Issue by deepconsc** [dhgrs/chainer-Fast-WaveNet#6]
Is there any samples to see the quality of generated sounds?
Additionally, what is the generation time?

**Comment by dhgrs** [comment]
I didn't upload some generated sounds based on this repository. My best autoregressive WaveNet implementation is [ClariNet](https://github.com/dhgrs/chainer-ClariNet) so that please check it instead of this repository.
And both of my implementations are not optimized. So that it takes too long to generate audio. About 30 samples / sec.
